#!/bin/sh
# tiktok - a simple CLI tool to interact with the TikTok text-to-speech API
# currently only supports macOS

usage() {
    echo "Usage: $0 -s session_id [-v voice] [-o file] [text...]"
    echo "Options:"
    echo "  -s session_id  Session ID to use"
    echo "  -v voice       Voice to use (default: en_us_001)"
    echo "                 see https://github.com/oscie57/tiktok-voice/blob/main/codes.md for available voices"
    echo "  -o file        Output file, default is to play audio to the speakers"
}

voice='en_us_001'
session=''
while getopts "hs:v:o:" opt; do
    case $opt in
    v)
        voice=$OPTARG
        ;;
    o)
        output=$OPTARG
        ;;
    s)
        session=$OPTARG
        ;;
    h)
        usage
        exit 0
        ;;
    *)
        usage
        exit 1
        ;;
    esac
done

shift $((OPTIND - 1))
text=$@
if [ -z "$text" ]; then
    text=$(cat)
fi

temp=$(mktemp)
response=$(curl -X POST -G -s 'https://api.tiktokv.com/media/api/text/speech/invoke/' \
    --data-urlencode "text_speaker=$voice" \
    --data-urlencode "req_text=$text" \
    --data-urlencode 'speaker_map_type=0' \
    --data-urlencode 'aid=1233' \
    --header "Cookie: sessionid=$session"
)
message=$(echo $response | jq -r '.message')
if [ "$message" != 'success' ]; then
    echo "Error: $message"
    exit 1
fi
echo $response | jq -r '.data.v_str' | base64 -d > $temp

if [ -n "$output" ]; then
    mv $temp $output
else
    afplay $temp
    rm $temp
fi
